version: '3.7'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:16-alpine3.15
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_PORT=0 # https://github.com/facebook/create-react-app/issues/11779
